name: Development Wiki Sync

on:
  push:
    branches:
      - development
    paths:
      - 'pages/**'

jobs:
  sync:
    name: Synchronize Wiki
    runs-on: ubuntu-latest
    if: github.repository == 'PolyhedralDev/TerraWiki'
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v2
      - name: Syncing
        run: sh src/sync.sh PolyhedralDev/TerraWiki.wiki.git
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
